version: '3.4'

services:
  lbhtenancyapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  stubuniversalhousing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

