version: '3.2'

services:
  lbhtenancyapi:
    image: lbhtenancyapi
    build:
      context: .
      dockerfile: LBHTenancyAPI/Dockerfile
    ports:
      - 3000:80
  lbhtenancyapitest:
    image: lbhtenancyapitest
    build:
      context: .
      dockerfile: LBHTenancyAPITest/Dockerfile
  stubuniversalhousing:
    image: stubuniversalhousing
    build:
      context: .
      dockerfile: StubUniversalHousing/Dockerfile
    ports:
      - 1433:1433
